# Generated by Django 5.0 on 2026-03-07 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
        ("members", "0001_initial"),
        ("organisation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="members.member",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organisation.zone",
            ),
        ),
    ]
